#------------DATASET CONFIG-------------
NAME: "COCO"
DATASET_PATH : "/home/yangqi/dataspace/COCO/"
MEAN: [0.485, 0.456, 0.406]
STD: [0.229, 0.224, 0.225]
NUM_CLASSES: 21  # COCO has 80 classes + 1 background, but we use the VOC classes
BASE_SIZE: 512
CROP_SIZE: 512
MAP_LIST : [5, 2, 16, 9, 44, 6, 3, 17, 62, 21, 67, 18, 19, 4,
    1, 64, 20, 63, 7, 72] # 90 ids -> 20 classes   from 1 to 90 (20 numbers)
CLASS_LABEL : [5,2,15,9,40,6,3,16,57,20,61,17,18,4,1,59,19,58,7,63]
#  None  : 0  ignore
#  airplane
#  bicycle
#  bird
#  boat
#  bottle
#  bus
#  car
#  cat
#  chair
#  cow
#  dining table
#  dog
#  horse
#  motorcycle
#  person
#  potted plant
#  sheep
#  couch
#  train
#  tv